# Generated by Django 4.0.4 on 2022-07-14 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='image/profile_pic', verbose_name='Profile Picture')),
                ('gender', models.CharField(choices=[('-', '---'), ('M', 'Male'), ('F', 'Female')], default='-', max_length=1, verbose_name='Gender')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug Fields')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
